name: 'Terrafrm Format (fmt)'
description: 'This action uses the `terraform fmt` command to check that all terraform files in a terraform configuration directory are in the canonical format.'
author: 'Benoit Blais'

inputs:
  target:
    description: 'Target to the terraform configuration.'
    required: false
    type: string
  recursive:
    description: 'By default, fmt scans the current directory for configuration files. If you provide a file or a directory for the target argument, then fmt will scan that file or that directory instead.'
    required: false
    default: true
    type: boolean
  comment:
    description: 'Whether or not to comment on GitHub pull requests. Defaults to `false`.'
    required: false
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - id: BashScript
      shell: bash
      run: bash ${{ github.action_path }}/main.sh
      env:
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_RECURSIVE: ${{ inputs.recursive }}
        INPUT_COMMENT: ${{ inputs.comment }}
        